export const VIRTUALIZATION = {
  INITIAL_RANGE: { start: 0, end: 4 } as const,
  DEFAULT_BUFFER_SIZE: 4,
  DEFAULT_THRESHOLD: 0.9,
  DEFAULT_ITEM_HEIGHT: 150,
  ANIMATION_DURATION: 300,
  MAX_EXPANDED_HEIGHT: 1000,
} as const;
